; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:board]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32doit-devkit-v1
framework = arduino

# To get the secrets
extra_scripts = pre:load_secrets.py

# using the latest stable version
lib_deps = ESP32Async/ESPAsyncWebServer

# OTA
upload_protocol = espota
# upload_port & upload_flags are set by the secrets script

# For serial monitor
monitor_speed = 115200

# Used for the first upload
[env:usb]
extends = env:board
upload_protocol = esptool
